n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('O valor é Numérico?:', n.isnumeric())
print('O valor é AlphaNumn?:', n.isalnum())
print('O valor é Alfabético?:', n.isalpha())
print('O valor está em Maiusculo?:', n.isupper())
print('O valor é Decimal?:', n.isdecimal())
print('O valor está em Minusculo?:', n.islower())
print('O valor está capitalizado?:', n.istitle())
